# Generated by Django 4.1.4 on 2023-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("link_address", models.URLField(verbose_name="Ссылка")),
                (
                    "link_for_messenger",
                    models.BooleanField(default=False, verbose_name="Мессенджер"),
                ),
                (
                    "link_for_social_network",
                    models.BooleanField(default=False, verbose_name="Социальная сеть"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка",
                "verbose_name_plural": "Ссылки",
                "ordering": ["link_address"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("address", models.TextField(max_length=256, verbose_name="Адрес")),
                (
                    "work_schedule",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "phone_number_cell",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Мобильный телефон",
                    ),
                ),
                (
                    "phone_number_home",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Городской телефон",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "entance_diagram",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Схема прохода в здание",
                    ),
                ),
                (
                    "parking_place",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Место для парковки",
                    ),
                ),
                (
                    "yandex_map",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Карта на базе сервиса Яндекс.Карты",
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contacts",
                        to="contacts.link",
                        verbose_name="Ссылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["address"],
            },
        ),
    ]
