# Generated by Django 4.1.7 on 2023-04-17 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company_description", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicdescription",
            options={"ordering": ["id"], "verbose_name": "Настройки описания клиники"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["id"], "verbose_name": "Настройки контактов"},
        ),
        migrations.AlterModelOptions(
            name="patientinfo",
            options={
                "ordering": ["id"],
                "verbose_name": "Настройка информации для пациентов",
            },
        ),
    ]
