# Generated by Django 4.1.7 on 2023-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_description", "0002_alter_clinicdescription_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClinicImage",
            new_name="CompanyImage",
        ),
        migrations.AlterModelOptions(
            name="link",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Ссылка",
                "verbose_name_plural": "Ссылки",
            },
        ),
        migrations.AddField(
            model_name="link",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
