# Generated by Django 4.1.7 on 2023-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "company_description",
            "0003_rename_clinicimage_companyimage_alter_link_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_approach_description",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Описание подхода к клиенту",
                    ),
                ),
                (
                    "video",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Видеоролик с выступлением директора компании",
                    ),
                ),
                (
                    "company_main_director_description",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Описание директора компании",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фото главного врача в клинике",
                    ),
                ),
                (
                    "company_history",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="История компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки описания клиники",
                "ordering": ["id"],
            },
        ),
        migrations.DeleteModel(
            name="ClinicDescription",
        ),
    ]
