# Generated by Django 4.1.7 on 2023-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "task_description",
                    models.TextField(max_length=1024, verbose_name="Задача"),
                ),
                (
                    "problem_solve",
                    models.TextField(
                        blank=True, max_length=4096, null=True, verbose_name="Решение"
                    ),
                ),
                (
                    "patient_result",
                    models.TextField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Результат для пациента",
                    ),
                ),
                (
                    "image_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фото пациента",
                    ),
                ),
                ("video", models.URLField(blank=True, null=True, verbose_name="Видео")),
                (
                    "completion_date_result",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Срок достижения результата",
                    ),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="portfolios",
                        to="employees.employee",
                        verbose_name="Врачи",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="portfolios",
                        to="services.service",
                        verbose_name="Услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Портфолио",
                "verbose_name_plural": "Портфолио",
                "ordering": ["task_description"],
            },
        ),
    ]
