# Generated by Django 4.1.7 on 2023-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("full_name", models.CharField(max_length=256, verbose_name="ФИО")),
                (
                    "image_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фотография сотрудника",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("full_name", models.CharField(max_length=256, verbose_name="ФИО")),
                (
                    "image_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фотография сотрудника",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Руководитель",
                "verbose_name_plural": "Руководители",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCertificateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Имя изображения"),
                ),
                (
                    "path",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="Изображение"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEducationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Имя изображения"),
                ),
                (
                    "path",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="Изображение"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Образование врача",
                "verbose_name_plural": "Образование врача",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="JuniorMedicalStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("full_name", models.CharField(max_length=256, verbose_name="ФИО")),
                (
                    "image_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фотография сотрудника",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Врач младшего медперсонала",
                "verbose_name_plural": "Врачи младшего медперсонала",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("full_name", models.CharField(max_length=256, verbose_name="ФИО")),
                (
                    "image_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фотография сотрудника",
                    ),
                ),
                (
                    "image_patient_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фотография врача с пациентом",
                    ),
                ),
                (
                    "video",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Видео с представлением врача",
                    ),
                ),
                (
                    "specialization",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Навыки врача",
                    ),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Стаж работы"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "certificate_images",
                    models.ManyToManyField(
                        blank=True,
                        to="employees.employeecertificateimage",
                        verbose_name="Сертификаты",
                    ),
                ),
                (
                    "education_images",
                    models.ManyToManyField(
                        blank=True,
                        to="employees.employeeeducationimage",
                        verbose_name="Образование",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="doctors",
                        to="services.service",
                        verbose_name="Услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ["ordering"],
            },
        ),
    ]
