# Generated by Django 4.1.7 on 2023-03-27 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                max_length=256,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="meta_keywords",
            field=models.TextField(
                blank=True,
                default="",
                max_length=256,
                null=True,
                verbose_name="Ключевые слова",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="meta_title",
            field=models.TextField(
                blank=True,
                default="",
                max_length=256,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                default=django.utils.timezone.now,
                max_length=256,
                unique=True,
                verbose_name="URL",
            ),
            preserve_default=False,
        ),
    ]
