# Generated by Django 4.1.7 on 2023-04-23 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employee_meta_description_employee_meta_keywords_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JuniorMedicalStaff",
            new_name="JuniorStaff",
        ),
        migrations.AlterModelOptions(
            name="juniorstaff",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Младший персонал",
                "verbose_name_plural": "Младший персонал",
            },
        ),
    ]
